#include "CompilationEngine.hpp"
#include <cassert>

inline std::string CompilationEngine::tokenListKey(int offset) {
  return this->tokenList.at(this->tokenListIndex + offset)->begin()->first;
}
inline JackTypes::TokenType CompilationEngine::tokenListValue(int offset) {
  return this->tokenList.at(this->tokenListIndex + offset)->begin()->second;
}
/*With this I will be able to re-use the token-list generated by the tokenizer*/
/*I don't really get the whole process I think that the advance and stuff is to
 * move get token*/
/*and then let the compilation takes cares, nevertheless I will continue this
 * way then I will see*/
CompilationEngine::CompilationEngine(
    const std::vector<std::map<std::string, JackTypes::TokenType> *> &tokenList,
    const std::string &outputFilePath)
#ifdef DEBUG
    /*:outputFile(std::string("./test/output_test_1.xml")),*/  /*test_1*/
    /*: outputFile(std::string("./test/output_test_2.xml")),*/ /*test_2*/
    /*: outputFile(std::string("./test/output_test_3.xml")),*/ /*test_3*/
    /*: outputFile(std::string("./test/output_test_4.xml")),*/ /*test_4*/
    : outputFile(std::string("./test/output_test_5.xml")),     /*test_5*/
#else
    : outputFile(outputFilePath),
#endif

      tokenList(tokenList),
#ifdef DEBUG
      /*tokenListIndex(tokenList.size() - 6)*/ /*For test_1*/
      /*tokenListIndex(tokenList.size() - 6)*/ /*For test_2*/
      /*tokenListIndex(tokenList.size() - 1)*/ /*For test_3*/
      /*tokenListIndex(tokenList.size() - 1)*/ /*For test_4*/
      tokenListIndex(tokenList.size() - 4)     /*For test_5*/

#else
      tokenListIndex(0),
#endif
      flagIsDoStatement(false) {
}

void CompilationEngine::run() {
#ifndef DEBUG
  this->compileClass();
#else
  this->compileExpression();
#endif
}

void CompilationEngine::writeToFileStartNonTerminal(
    const std::string &nonTerminal) {
  this->outputFile << "\t" << nonTerminal << "\n";
  return;
}
void CompilationEngine::writeToFileFinishNonTerminal(
    const std::string &nonTerminal) {
  this->outputFile << nonTerminal << "\n";
  return;
}
void CompilationEngine::writeToFile() {
  JackTypes::TokenType tokenType = this->tokenListValue();
  const std::string &token = this->tokenListKey();

  /*identation*/
  this->outputFile << "\t";

  switch (tokenType) {
  case JackTypes::KEYWORD:
    this->outputFile << "<keyword> " << token << " </keyword>" << "\n";
    break;
  case JackTypes::SYMBOL: {
    std::string symbol = token;
    if (token == "<")
      symbol = "&lt;";
    if (token == ">")
      symbol = "&gt;";
    if (token == "\"")
      symbol = "quot;";
    if (token == "&")
      symbol = "&amp;";

    this->outputFile << "<symbol> " << symbol << " </symbol>" << "\n";
  } break;
  case JackTypes::IDENTIFIER:
    this->outputFile << "<identifier> " << token << " </identifier>"
                     << "\n";
    break;
  case JackTypes::INT_CONST:
    this->outputFile << "<integerConstant> " << token << " </integerConstant>"
                     << "\n";
    break;
  case JackTypes::STRING_CONST:
    this->outputFile << "<stringConstant> " << token << " </stringConstant>"
                     << "\n";
    break;
  default:
    break;
  }
}

/*Do a kind of wrapper of the following*/
void CompilationEngine::compileClass() {
  /*to improve this*/
  this->writeToFileStartNonTerminal("<class>");

  if (!(this->tokenListKey() == "class"))
    return;
  this->writeToFile();
  this->tokenListIndex++;
  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return;
  this->writeToFile();
  this->tokenListIndex++;
  if (!(this->tokenListKey() == "{"))
    return;
  this->writeToFile();
  this->tokenListIndex++;

  while (this->compileClassVarDec())
    ;

  while (this->compileSubroutine())
    ;

  if (!(this->tokenListKey() == "}"))
    return;
  this->writeToFile();
  this->tokenListIndex++;

  this->writeToFileFinishNonTerminal("</class>");
  return;
}
bool CompilationEngine::compileClassVarDec() {

  if (!(this->tokenListKey() == "static" || this->tokenListKey() == "field"))
    return false;

  this->writeToFileStartNonTerminal("<classVarDec>");

  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "int" || this->tokenListKey() == "char" ||
        this->tokenListKey() == "boolean" ||
        this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  while ((this->tokenListKey() == ",") &&
         /*offset */
         (this->tokenListValue(1) == JackTypes::IDENTIFIER)) {

    this->writeToFile();
    this->tokenListIndex++;
    this->writeToFile();
    this->tokenListIndex++;
  }
  if (!(this->tokenListKey() == ";"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  this->writeToFileFinishNonTerminal("</classVarDec>");

  return true;
}
bool CompilationEngine::compileSubroutine() {

  if (!(this->tokenListKey() == "constructor" ||
        this->tokenListKey() == "function" || this->tokenListKey() == "method"))
    return false;

  this->writeToFileStartNonTerminal("<subroutineDec>");

  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "void" || this->tokenListKey() == "int" ||
        this->tokenListKey() == "char" || this->tokenListKey() == "boolean" ||
        this->tokenListValue() == JackTypes::IDENTIFIER))

    return false;

  this->writeToFile();
  this->tokenListIndex++;

  /*subroutine name*/
  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "("))
    return false;
  this->writeToFile();
  this->tokenListIndex++;

  //  this->flagIsDoStatement = false;
  this->compileParameterList();
  //  this->flagIsDoStatement = true;

  if (!(this->tokenListKey() == ")"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  /*This needs to be in another function*/
  /*subroutine body*/
  if (!this->compileSubroutineBody())
    return false;

  this->writeToFileFinishNonTerminal("</subroutineDec>");

  return true;
}
bool CompilationEngine::compileSubroutineBody() {

  if (!(this->tokenListKey() == "{"))
    return false;

  this->writeToFileStartNonTerminal("<subroutineBody>");
  this->writeToFile();
  this->tokenListIndex++;

  while (this->compileVarDec())
    ;

  this->compileStatements();

  if (!(this->tokenListKey() == "}"))
    return false;
  this->writeToFile();
  this->tokenListIndex++;
  this->writeToFileFinishNonTerminal("</subroutineBody>");

  return true;
}
bool CompilationEngine::compileStatements() {
  this->writeToFileFinishNonTerminal("<statements>");
  while (this->compileLet() || this->compileIf() || this->compileWhile() ||
         this->compileDo() || this->compileReturn())
    ;
  this->writeToFileFinishNonTerminal("</statements>");
  return true;
}
bool CompilationEngine::compileLet() {

  if (!(this->tokenListKey() == "let"))
    return false;

  this->writeToFileFinishNonTerminal("<letStatement>");
  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  if (this->tokenListKey() == "[") {

    this->writeToFile();
    this->tokenListIndex++;

    //    this->flagIsDoStatement = false;

    if (!this->compileExpression()) /*this->compileExpression();*/
      return false;

    //    this->flagIsDoStatement = true;

    if (!(this->tokenListKey() == "]"))
      return false;

    this->writeToFile();
    this->tokenListIndex++;
  }
  if (!(this->tokenListKey() == "="))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  //// this->flagIsDoStatement = false;

  if (!this->compileExpression()) /*this->compileExpression();*/
    return false;
  //// this->flagIsDoStatem/* en */t = true;

  if (!(this->tokenListKey() == ";"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  this->writeToFileFinishNonTerminal("</letStatement>");

  return true;
}

bool CompilationEngine::compileIf() {

  if (!(this->tokenListKey() == "if"))
    return false;

  this->writeToFileFinishNonTerminal("<ifStatement>");
  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "("))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  //  this->flagIsDoStatement = false;
  if (!this->compileExpression()) /*this->compileExpression();*/
    return false;
  //  this->flagIsDoStatement = true;

  if (!(this->tokenListKey() == ")"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "{"))
    return false;
  this->writeToFile();
  this->tokenListIndex++;

  if (!this->compileStatements()) /*this->compileStatements();*/
    return false;

  if (!(this->tokenListKey() == "}"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  if (this->tokenListKey() == "else") {
    this->writeToFile();
    this->tokenListIndex++;
    if (!(this->tokenListKey() == "{"))
      return false;

    this->writeToFile();
    this->tokenListIndex++;
    if (!this->compileStatements())
      return false;
    if (!(this->tokenListKey() == "}"))
      return false;

    this->writeToFile();
    this->tokenListIndex++;
  }
  this->writeToFileFinishNonTerminal("</ifStatement>");

  return true;
}
bool CompilationEngine::compileWhile() {

  if (!(this->tokenListKey() == "while"))
    return false;

  this->writeToFileFinishNonTerminal("<whileStatement>");
  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "("))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  //  this->flagIsDoStatement = false;
  if (!this->compileExpression()) /*this->compileExpression();*/
    return false;
  //  this->flagIsDoStatement = true;

  if (!(this->tokenListKey() == ")"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "{"))
    return false;
  this->writeToFile();
  this->tokenListIndex++;

  // this->flagIsDoStatement = false;
  if (!this->compileStatements()) /*this->compileStatements();*/
    return false;
  //  this->flagIsDoStatement = true;

  if (!(this->tokenListKey() == "}"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  this->writeToFileFinishNonTerminal("</whileStatement>");
  return true;
}
bool CompilationEngine::compileDo() {

  if (!(this->tokenListKey() == "do"))
    return false;

  this->writeToFileFinishNonTerminal("<doStatement>");
  this->writeToFile();
  this->tokenListIndex++;

  // int iteration = 0;
  // bool succesfull = true;
  // std::cout << "HEREEE" << "\n";
  // this->compileTerm(&iteration, &succesfull);
  // if (!succesfull)
  // return false;
  this->flagIsDoStatement = true;
  if (!this->compileExpression())
    return false;
  this->flagIsDoStatement = false;

  if (!(this->tokenListKey() == ";"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  this->writeToFileFinishNonTerminal("</doStatement>");
  return true;
}
bool CompilationEngine::compileReturn() {

  if (!(this->tokenListKey() == "return"))
    return false;

  this->writeToFileFinishNonTerminal("<returnStatement>");
  this->writeToFile();
  this->tokenListIndex++;

  //  this->flagIsDoStatement = false;
  if (!this->compileExpression())
    return false;
  //  this->flagIsDoStatement = true;

  if (!(this->tokenListKey() == ";"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  this->writeToFileFinishNonTerminal("</returnStatement>");
  return true;
}

void CompilationEngine::compileParameterList() {

  /*Check there are no parameters*/
  if (this->tokenListKey() == ")") {
    this->writeToFileStartNonTerminal("<parameterList>");
    this->writeToFileFinishNonTerminal("</parameterList>");
    return;
  }

  if (!(this->tokenListKey() == "int" || this->tokenListKey() == "char" ||
        this->tokenListKey() == "boolean" ||
        this->tokenListValue() == JackTypes::IDENTIFIER))
    return;

  this->writeToFileStartNonTerminal("<parameterList>");
  this->writeToFile();
  this->tokenListIndex++;
  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return;

  this->writeToFile();
  this->tokenListIndex++;

  while ((this->tokenListKey() == ",") &&
         (this->tokenListKey(1) == "int" || this->tokenListKey(1) == "char" ||
          this->tokenListKey(1) == "boolean" ||
          this->tokenListValue(1) == JackTypes::IDENTIFIER) &&
         /*offset */
         (this->tokenListValue(2) == JackTypes::IDENTIFIER)) {
    this->writeToFile();
    this->tokenListIndex++;
    this->writeToFile();
    this->tokenListIndex++;
    this->writeToFile();
    this->tokenListIndex++;
  }
  this->writeToFileFinishNonTerminal("</parameterList>");

  return;
}
bool CompilationEngine::compileExpression() {
  /*if expression is empty*/
  if (this->tokenListKey() == ";")
    return true;

  int iteration = 0;
  bool succesfull = true;

  if (!this->flagIsDoStatement)
    this->writeToFileStartNonTerminal("<expression>");

  /*for be working just now*/
  this->compileTerm(&iteration, &succesfull);
  if (!succesfull)
    return false;

  iteration = 0;
  succesfull = true;

  /*not like this because I need to update the index*/
  while (true) {
    if ((size_t)this->tokenListIndex > this->tokenList.size() - 1)
      break;

    if (this->tokenListKey() == "-") {
      std::cout << "IN COMPILE_EXPRESSION:\t" << "\n";
      std::cout << "PREVIOUS TOKEN:\t" << this->tokenListKey(-1) << "\n";
      std::cout << "NEXT TOKEN:\t" << this->tokenListKey(+1) << "\n";
    }
    if (!JackTypes::tokenIsOp(this->tokenListKey()))
      break;

    this->writeToFile();
    this->tokenListIndex++;
    this->compileTerm(&iteration, &succesfull);
    if (!succesfull)
      return false;
  }
  if (!this->flagIsDoStatement) {
    this->writeToFileFinishNonTerminal("</expression>");
    // this->flagIsDoStatement = false; /*Hard to understand*/
  }

  return true;
}
void CompilationEngine::compileTerm(int *iteration, bool *succesfull) {

  /*this will be the same */
  /*never theless the tokenListIndex will be incremented because is global*/

  // int localIteration = *iteration;

  if ((size_t)this->tokenListIndex > this->tokenList.size() - 1) {
    return;
  }

  /*First check that term is correct*/
  if (JackTypes::INT_CONST == this->tokenListValue() ||
      JackTypes::STRING_CONST == this->tokenListValue() ||
      JackTypes::KEYWORD == this->tokenListValue()) {
    if (!this->flagIsDoStatement)
      this->writeToFileStartNonTerminal("<term>");
    this->writeToFile();
    *iteration += 1;
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    if (!this->flagIsDoStatement)
      this->writeToFileFinishNonTerminal("</term>");
    return;
  }

  if (this->tokenListValue() == JackTypes::IDENTIFIER &&
      this->tokenListKey(1) == "[") {
    if (!this->flagIsDoStatement)
      this->writeToFileStartNonTerminal("<term>");
    this->writeToFile();
    this->tokenListIndex++;
    if (this->tokenListKey() == "[") {
      this->writeToFile();
      this->tokenListIndex++;
      if (!this->compileExpression()) {
        *succesfull = false;
        return;
      }
      if (!(this->tokenListKey() == "]")) {
        *succesfull = false;
        return;
      }
      *iteration += 1;
      this->writeToFile();
      this->tokenListIndex++;
      this->compileTerm(iteration, succesfull);
      if (!this->flagIsDoStatement)
        this->writeToFileFinishNonTerminal("</term>");
      return;
    }
  }
  if ((this->tokenListValue() == JackTypes::IDENTIFIER &&
       this->tokenListKey(1) == "(")) {
    if (!this->flagIsDoStatement)
      this->writeToFileStartNonTerminal("<term>");
    if (!this->_compileSubroutineCall()) {
      *succesfull = false;
      return;
    }
    *iteration += 1;
    this->compileTerm(iteration, succesfull);
    if (!this->flagIsDoStatement)
      this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  if ((this->tokenListValue() == JackTypes::IDENTIFIER &&
       this->tokenListKey(1) == ".")) {
    if (!this->flagIsDoStatement)
      this->writeToFileStartNonTerminal("<term>");
    this->writeToFile();
    this->tokenListIndex++;
    this->writeToFile();
    this->tokenListIndex++;
    if (!this->_compileSubroutineCall()) {
      *succesfull = false;
      return;
    }
    *iteration += 1;
    this->compileTerm(iteration, succesfull);
    if (!this->flagIsDoStatement)
      this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  if (this->tokenListValue() == JackTypes::IDENTIFIER) {
    if (!this->flagIsDoStatement)
      this->writeToFileStartNonTerminal("<term>");
    this->writeToFile();
    *iteration += 1;
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    if (!this->flagIsDoStatement)
      this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  if (this->tokenListKey() == "(") {
    if (!this->flagIsDoStatement)
      this->writeToFileStartNonTerminal("<term>");
    this->writeToFile();
    this->tokenListIndex++;
    if (!this->compileExpression()) {
      *succesfull = false;
      return;
    }
    if (!(this->tokenListKey() == ")")) {
      *succesfull = false;
      return;
    }
    *iteration += 1;
    this->writeToFile();
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    if (!this->flagIsDoStatement)
      this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  if (JackTypes::tokenIsUnaryOp(this->tokenListKey()) && *iteration == 0) {
    std::cout << "ITERATION:\t" << *iteration << "\n";
    std::cout << "PREVIOUS TOKEN:\t" << this->tokenListKey(-1) << "\n";
    std::cout << "NEXT TOKEN:\t" << this->tokenListKey(+1) << "\n";
    if (!this->flagIsDoStatement)
      this->writeToFileStartNonTerminal("<term>");
    this->writeToFile();
    *iteration += 1;
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    if (!this->flagIsDoStatement)
      this->writeToFileFinishNonTerminal("</term>");
    return;
  }

  if (JackTypes::tokenIsKeywordConstant(this->tokenListKey())) {
    if (!this->flagIsDoStatement)
      this->writeToFileStartNonTerminal("<term>");
    this->writeToFile();
    *iteration += 1;
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    if (!this->flagIsDoStatement)
      this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  return;
}

/*Personal idea*/
bool CompilationEngine::_compileSubroutineCall() {

  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "("))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  bool old_state_flag = this->flagIsDoStatement;

  this->flagIsDoStatement = false;
  this->compileExpressionList();
  this->flagIsDoStatement = old_state_flag;

  if (!(this->tokenListKey() == ")"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;
  return true;
}

bool CompilationEngine::compileVarDec() {

  if (!(this->tokenListKey() == "var"))
    return false;

  this->writeToFileFinishNonTerminal("<varDec>");
  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "int" || this->tokenListKey() == "char" ||
        this->tokenListKey() == "boolean" ||
        this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  while ((this->tokenListKey() == ",") &&
         /*offset */
         (this->tokenListValue(1) == JackTypes::IDENTIFIER)) {
    this->writeToFile();
    this->tokenListIndex++;
    this->writeToFile();
    this->tokenListIndex++;
  }

  if (!(this->tokenListKey() == ";"))
    return false;

  this->writeToFile();
  this->tokenListIndex++;

  this->writeToFileFinishNonTerminal("</varDec>");

  return true;
}
void CompilationEngine::compileExpressionList() {
  this->writeToFileStartNonTerminal("<expressionList>");
  if (this->tokenListKey() == ")") {
    this->writeToFileFinishNonTerminal("</expressionList>");
    return;
  }

  /*code*/
  if (!this->compileExpression())
    return;

  while (true) {
    if (!(this->tokenListKey() == ","))
      break;
    this->writeToFile();
    this->tokenListIndex++;
    // this->flagIsDoStatement = false;
    if (!this->compileExpression())
      break;
  }

  this->writeToFileFinishNonTerminal("</expressionList>");

  return;
}

const std::vector<std::map<std::string, JackTypes::TokenType> *> &
CompilationEngine::getTokenList() {
  return this->tokenList;
}
CompilationEngine::~CompilationEngine() {
  std::cout << "Calling compilation engine destructor" << "\n";
}
