#include "CompilationEngine.hpp"
#include "SymbolTable.hpp"
#include "Types.hpp"
#include "VmWritter.hpp"
#include <cassert>
#include <cmath>
#include <cstddef>
#include <ios>
#include <regex>
#include <sstream>
#include <stack>
#include <string>

inline std::string CompilationEngine::tokenListKey(int offset) {
  return this->tokenList.at(this->tokenListIndex + offset)->begin()->first;
}
inline JackTypes::TokenType CompilationEngine::tokenListValue(int offset) {
  return this->tokenList.at(this->tokenListIndex + offset)->begin()->second;
}
/*With this I will be able to re-use the token-list generated by the tokenizer*/
/*I don't really get the whole process I think that the advance and stuff is to
 * move get token*/
/*and then let the compilation takes cares, nevertheless I will continue this
 * way then I will see*/
CompilationEngine::CompilationEngine(
    const std::vector<std::map<std::string, JackTypes::TokenType> *> &tokenList,
    const std::string &outputFilePath)
    :
#ifdef DEBUG
/*:outputFile(std::string("./test/output_test_1.xml")),*/  /*test_1*/
/*: outputFile(std::string("./test/output_test_2.xml")),*/ /*test_2*/
/*: outputFile(std::string("./test/output_test_3.xml")),*/ /*test_3*/
/*: outputFile(std::string("./test/output_test_4.xml")),*/ /*test_4*/
/*: outputFile(outputFilePath),*/                          /*test_5*/
#else
#endif
      tokenList(tokenList),
#ifdef DEBUG
/*tokenListIndex(tokenList.size() - 6)*/  /*For test_1*/
/*tokenListIndex(tokenList.size() - 6)*/  /*For test_2*/
/*tokenListIndex(tokenList.size() - 1)*/  /*For test_3*/
/*tokenListIndex(tokenList.size() - 1)*/  /*For test_4*/
/*tokenListIndex(tokenList.size() - 4),*/ /*For test_5*/

#else
      tokenListIndex(0),
#endif
      flagIsDoStatement(false), classSymbolTable(SymbolTable()),
      subroutineSymbolTable(SymbolTable()),
      subroutineTable(std::map<std::string, std::string>()),
      vmWritter(VmWritter(outputFilePath)), labelCounter(0) {
}

void CompilationEngine::run() {
#ifndef DEBUG
  this->populateSubroutineTable();
  this->compileClass();
#else
  // this->compileExpression();
  /*TEST with
   * x + g(2,y,-z)*5
   * a + b * c
   * x + y -2
   * foo(x,y+1,-7)
   * */
  // std::string test = "x+g(2,y,-z)*5";
  // this->_codeWrite(test);
  while (this->compileIf())
    ;

#endif
}

// void CompilationEngine::writeToFileStartNonTerminal(
//     const std::string &nonTerminal) {
//   this->outputFile << "\t" << nonTerminal << "\n";
//   return;
// }
// void CompilationEngine::writeToFileFinishNonTerminal(
//     const std::string &nonTerminal) {
//   this->outputFile << nonTerminal << "\n";
//   return;
// }
void CompilationEngine::writeToFile() { return; }
// void CompilationEngine::writeToFile() {
//   JackTypes::TokenType tokenType = this->tokenListValue();
//   const std::string &token = this->tokenListKey();
//
//   /*identation*/
//   this->outputFile << "\t";
//
//   switch (tokenType) {
//   case JackTypes::KEYWORD:
//     this->outputFile << "<keyword> " << token << " </keyword>" << "\n";
//     break;
//   case JackTypes::SYMBOL: {
//     std::string symbol = token;
//     if (token == "<")
//       symbol = "&lt;";
//     if (token == ">")
//       symbol = "&gt;";
//     if (token == "\"")
//       symbol = "quot;";
//     if (token == "&")
//       symbol = "&amp;";
//
//     this->outputFile << "<symbol> " << symbol << " </symbol>" << "\n";
//   } break;
//   case JackTypes::IDENTIFIER:
//     this->outputFile << "<identifier> " << token << " </identifier>"
//                      << "\n";
//     break;
//   case JackTypes::INT_CONST:
//     this->outputFile << "<integerConstant> " << token << "
//     </integerConstant>"
//                      << "\n";
//     break;
//   case JackTypes::STRING_CONST:
//     this->outputFile << "<stringConstant> " << token << " </stringConstant>"
//                      << "\n";
//     break;
//   default:
//     break;
//   }
// }

/*Do a kind of wrapper of the following*/
void CompilationEngine::compileClass() {
  /*to improve this*/
  // this->writeToFileStartNonTerminal("<class>");

  if (!(this->tokenListKey() == "class"))
    return;
  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return;

  /*This should be the class name i will need later*/
  this->currentClass = this->tokenListKey();

  // this->writeToFile();
  this->tokenListIndex++;
  if (!(this->tokenListKey() == "{"))
    return;
  // this->writeToFile();
  this->tokenListIndex++;

  while (this->compileClassVarDec())
    ;

  while (this->compileSubroutine())
    ;

  if (!(this->tokenListKey() == "}"))
    return;
  // this->writeToFile();
  this->tokenListIndex++;

  // this->writeToFileFinishNonTerminal("</class>");
  return;
}
bool CompilationEngine::compileClassVarDec() {

  if (!(this->tokenListKey() == "static" || this->tokenListKey() == "field"))
    return false;

  /*Needed for the created variable sin the while loop*/
  std::string kind = this->tokenListKey();

  this->classSymbolTable.setSymbol(this->classSymbolTable.allocateSymbol());

  // this->writeToFileStartNonTerminal("<classVarDec>");

  this->classSymbolTable.getCurrentSymbol()->setKind(this->tokenListKey());
  // this->writeToFile();
  this->tokenListIndex++;

  /* this-classSymbolTable.allocatedSymbol();*/
  /*this->classSymbolTable.addSymbol()*/

  if (!(this->tokenListKey() == "int" || this->tokenListKey() == "char" ||
        this->tokenListKey() == "boolean" ||
        this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  /*Needed for the created variable sin the while loop*/
  std::string type = this->tokenListKey();
  this->classSymbolTable.getCurrentSymbol()->setType(this->tokenListKey());
  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->classSymbolTable.getCurrentSymbol()->setName(this->tokenListKey());
  this->classSymbolTable.addSymbol(this->classSymbolTable.getCurrentSymbol());
  this->classSymbolTable.setSymbol(nullptr);

  // this->writeToFile();
  this->tokenListIndex++;

  while ((this->tokenListKey() == ",") &&
         /*offset */
         (this->tokenListValue(1) == JackTypes::IDENTIFIER)) {

    /*Improve this maybe*/
    this->classSymbolTable.setSymbol(this->classSymbolTable.allocateSymbol());
    this->classSymbolTable.getCurrentSymbol()->setKind(kind);
    this->classSymbolTable.getCurrentSymbol()->setType(type);
    this->classSymbolTable.getCurrentSymbol()->setName(this->tokenListKey(1));
    this->classSymbolTable.addSymbol(this->classSymbolTable.getCurrentSymbol());
    this->classSymbolTable.setSymbol(nullptr);
    /*
     * this-classSymbolTable.allocateSymbol();
     * this->classSymbolTable.addSymbol();
     *
     * */
    // this->writeToFile();
    this->tokenListIndex++;
    // this->writeToFile();
    this->tokenListIndex++;
  }
  if (!(this->tokenListKey() == ";"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  // this->writeToFileFinishNonTerminal("</classVarDec>");

  return true;
}
bool CompilationEngine::compileSubroutine() {

  if (!(this->tokenListKey() == "constructor" ||
        this->tokenListKey() == "function" || this->tokenListKey() == "method"))
    return false;

  /* This will need to be improved from now is not my main focus*/
  this->currentSubroutineType = this->tokenListKey();

  // this->writeToFileStartNonTerminal("<subroutineDec>");

  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "void" || this->tokenListKey() == "int" ||
        this->tokenListKey() == "char" || this->tokenListKey() == "boolean" ||
        this->tokenListValue() == JackTypes::IDENTIFIER))

    return false;

  this->tokenListIndex++;

  /*subroutine name*/
  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  /*This needs to be added for later when calling a subroutine*/
  this->subroutineTable.insert(
      {this->tokenListKey(), this->currentSubroutineType});

  this->currentSubroutine = this->tokenListKey();
  // this->writeToFile();
  //

  this->tokenListIndex++;

  if (!(this->tokenListKey() == "("))
    return false;
  // this->writeToFile();
  this->tokenListIndex++;

  //  this->flagIsDoStatement = false;

  /*putting function but I don't know if is correct*/

  /*For getting number of params*/
  int nArgsCounter = 0;
  this->compileParameterList(&nArgsCounter);

  // this->vmWritter.writeFunction(
  //     this->currentClass, subroutineName,
  //     this->subroutineSymbolTable.getLocalSymbolCounter());
  //  this->flagIsDoStatement = true;

  if (!(this->tokenListKey() == ")"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  /*This needs to be in another function*/
  /*subroutine body*/
  if (!this->compileSubroutineBody())
    return false;

  // this->vmWritter.writeFunction(
  //     this->currentClass, subroutineName,
  //     this->subroutineSymbolTable.getLocalSymbolCounter());

  /*Then I will put more order*/

  // this->writeToFileFinishNonTerminal("</subroutineDec>");

  // this->vmWritter.writeFunction(this->currentClass, subroutineName,
  //                               nArgsCounter);
  /*this->vmWritter.rese*/
  this->subroutineSymbolTable.resetSymbolTable();
  this->labelCounter = 0;

  return true;
}
bool CompilationEngine::compileSubroutineBody() {

  if (!(this->tokenListKey() == "{"))
    return false;

  // this->writeToFileStartNonTerminal("<subroutineBody>");
  // this->writeToFile();
  this->tokenListIndex++;

  while (this->compileVarDec())
    ;

  /*for correct symboltable*/

  if (this->currentSubroutineType == "function") {
    this->vmWritter.writeFunction(
        this->currentClass, this->currentSubroutine,
        this->subroutineSymbolTable.getLocalSymbolCounter());

  } else if (this->currentSubroutineType == "constructor") {
    this->vmWritter.writeFunction(
        this->currentClass, this->currentSubroutine,
        this->subroutineSymbolTable.getLocalSymbolCounter());
    /*Check lambda in c++*/
    int numberOfFields = this->classSymbolTable.getFieldSymbolCounter();
    /**/
    this->vmWritter.writePush("constant", numberOfFields);
    this->vmWritter.writeCall("Memory.alloc", 1);
    this->vmWritter.writePop("pointer", 0);
  } else if (this->currentSubroutineType == "method") {
    this->vmWritter.writeFunction(
        this->currentClass, this->currentSubroutine,
        this->subroutineSymbolTable.getLocalSymbolCounter());
    this->vmWritter.writePush("argument", 0);
    this->vmWritter.writePop("pointer", 0);
  }

  this->compileStatements();

  if (!(this->tokenListKey() == "}"))
    return false;
  // this->writeToFile();
  //
  this->tokenListIndex++;
  /*Returning object based address*/
  // this->vmWritter.writePush("pointer", 1);
  // this->writeToFileFinishNonTerminal("</subroutineBody>");

  return true;
}
bool CompilationEngine::compileStatements() {
  while (this->compileLet() || this->compileIf() || this->compileWhile() ||
         this->compileDo() || this->compileReturn())
    ;
  return true;
}
bool CompilationEngine::compileLet() {

  if (!(this->tokenListKey() == "let"))
    return false;

  this->tokenListIndex++;

  /*Now we are placed in the variable name*/
  /*Now considering that the variable make reference to a array location*/
  std::string expressionVariable = this->tokenListKey();
  SymbolTable::Symbol *symbol = this->_getSymbol(expressionVariable);

  /*Idkn if good idea I will create a flag */
  bool isArray = (this->tokenListKey(1) == "[") ? true : false;
  std::string saveAddress;
  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  /*if this condition if passed then we are in front of an array*/
  if (isArray) {

    /*pushing base address of the array then followed by the expression inside
     * the '[' ']'*/
    this->vmWritter.writePush(symbol->kind, symbol->posInSegment);

    // this->writeToFile();
    this->tokenListIndex++;

    //    this->flagIsDoStatement = false;

    int startExpressionIndex = this->tokenListIndex;

    if (!this->compileExpression()) /*this->compileExpression();*/
      return false;

    /*Just to test something*/
    std::string expression = "";
    for (int i = startExpressionIndex; i < this->tokenListIndex; i++)
      expression.append(this->tokenList.at(i)->begin()->first);

    std::cout << expression << "\n";
    saveAddress = std::string(expression);

    this->_codeWrite(expression);

    //    this->flagIsDoStatement = true;

    if (!(this->tokenListKey() == "]"))
      return false;

    this->vmWritter.writeArithmetic("add");
    this->vmWritter.writePop("pointer", 1);
    /*if save correct array cell to store*/
    // hasInnerArray =
    //     std::count_if(expression.begin(), expression.end(),
    //                   [](char letter) { return letter == '['; }) > 1;

    // if (hasInnerArray) {
    // this->vmWritter.writePush("pointer", 1);
    // this->vmWritter.writePop("temp", 2);
    // }

    // this->writeToFile();
    this->tokenListIndex++;
  }

  if (!(this->tokenListKey() == "="))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  int startExpressionIndex = this->tokenListIndex;

  if (!this->compileExpression()) /*this->compileExpression();*/
    return false;

  /*Just to test something*/
  std::string expression = "";
  for (int i = startExpressionIndex; i < this->tokenListIndex; i++) {
    expression.append(this->tokenList.at(i)->begin()->first);
  }

  std::cout << expression << "\n";
  /*When to put this is something I will figure it out after*/
  // if (expression == "true")
  //   expression = "-1";
  // if (expression == "false")
  //   expression = "0";

  this->_codeWrite(expression);

  if (!(this->tokenListKey() == ";"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  // /*Adding pop for the passed variable*/
  // SymbolTable::Symbol *symbol = this->_getSymbol(expressionVariable);
  // this->vmWritter.writePop(symbol->kind, symbol->posInSegment);

  // /*Adding pop for the passed variable*/
  // *symbol = this->_getSymbol(expressionVariable);
  // (!isArray) ? this->vmWritter.writePop(symbol->kind, symbol->posInSegment)
  //            : this->vmWritter.writePop("that", 0);
  if (!isArray)
    this->vmWritter.writePop(symbol->kind, symbol->posInSegment);
  else {
    // this->vmWritter.writePush("temp", 2);
    /*re-getting the address not usage of global variable*/
    this->vmWritter.writePush(symbol->kind,symbol->posInSegment);
    this->_codeWrite(saveAddress);
    this->vmWritter.writeArithmetic("add");

    this->vmWritter.writePop("pointer", 1);
    this->vmWritter.writePop("that", 0);
  }

  // this->writeToFileFinishNonTerminal("</letStatement>");

  return true;
}

bool CompilationEngine::compileIf() {

  if (!(this->tokenListKey() == "if"))
    return false;

  // this->writeToFileFinishNonTerminal("<ifStatement>");
  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "("))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;
  int startExpressionIndex = this->tokenListIndex;

  //  this->flagIsDoStatement = false;
  if (!this->compileExpression()) /*this->compileExpression();*/
    return false;
  //  this->flagIsDoStatement = true;
  //
  /*Just to test something*/
  std::string expression = "";
  for (int i = startExpressionIndex; i < this->tokenListIndex; i++)
    expression.append(this->tokenList.at(i)->begin()->first);

  std::cout << expression << "\n";
  this->_codeWrite(expression);

  if (!(this->tokenListKey() == ")"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "{"))
    return false;

  /*look ahead code  needs balanced curly brackets*/
  int isElseIf = false;
  std::stack<std::string> balancedCurlyBracket = std::stack<std::string>();
  balancedCurlyBracket.push(this->tokenListKey());
  size_t memoryTokenListIndex = this->tokenListIndex;
  this->tokenListIndex++;
  for (; (size_t)this->tokenListIndex < this->tokenList.size() - 1 &&
         !balancedCurlyBracket.empty();
       this->tokenListIndex++) {
    if (this->tokenListKey() == "}") {
      balancedCurlyBracket.pop();
    }
    if (this->tokenListKey() == "{") {
      balancedCurlyBracket.push(this->tokenListKey());
    }
  }
  (this->tokenListKey() == "else") ? isElseIf = true : isElseIf = false;
  /*Reset tokenListIndex after moving forward*/
  this->tokenListIndex = memoryTokenListIndex;

  // this->writeToFile();
  this->tokenListIndex++;

  this->vmWritter.writeArithmetic("~");

  // if (this->tokenListKey() != "else")
  //   this->vmWritter.writeIf(this->currentClass + "_" +
  //   this->currentSubroutine +
  //                           "_" + "end_if" + "_" +
  //                           std::to_string(this->labelCounter++));
  /*look ahead code  needs balanced curly brackets*/
  // std::stack<std::string> balancedCurlyBracket = std::stack<std::string>();
  // balancedCurlyBracket.push(this->tokenListKey());

  // size_t tmpTokenListIndex;
  // for (tmpTokenListIndex = this->tokenListIndex;
  //      tmpTokenListIndex < this->tokenList.size(); tmpTokenListIndex++) {
  //   if (this->tokenList.at(tmpTokenListIndex)->begin()->first == "}") {
  //     break;
  //   }
  // }
  // (this->tokenList.at(tmpTokenListIndex + 1)->begin()->first == "else")
  //     ? isElseIf = true
  //     : isElseIf = false;

  if (isElseIf)
    this->vmWritter.writeIf(this->currentClass + "_" + this->currentSubroutine +
                            "_" + "else_if" + "_" +
                            std::to_string(this->labelCounter++));
  else
    this->vmWritter.writeIf(this->currentClass + "_" + this->currentSubroutine +
                            "_" + "end_if" + "_" +
                            std::to_string(this->labelCounter++));

  /*Have memory of the iflabelCounter*/
  int ifLabelCounter = this->labelCounter;
  if (!this->compileStatements()) /*this->compileStatements();*/
    return false;

  /*At the end when returning the labelCounter will be the first called.
   * lifo so stack frames are going to be called each frame
   * will have a labelCounter locally but then when it finishes
   * it will return to the first compileIf and labelCounter will be 1
   *
   * */
  // this->labelCounter = ifLabelCounter;

  /*if condition true executed extament then go out of if*/
  this->vmWritter.writeGoto(this->currentClass + "_" + this->currentSubroutine +
                            "_" + "end_if" + "_" +
                            std::to_string(ifLabelCounter - 1));

  if (!(this->tokenListKey() == "}"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;
  /*Negate condition*/
  // this->vmWritter.writeArithmetic("~");
  //

  if (this->tokenListKey() == "else") {
    // this->writeToFile();
    /*add the label of the else*/
    this->vmWritter.writeLabel(this->currentClass + "_" +
                               this->currentSubroutine + "_" + "else_if" + "_" +
                               std::to_string(ifLabelCounter - 1));

    this->tokenListIndex++;
    if (!(this->tokenListKey() == "{"))
      return false;

    // this->writeToFile();
    this->tokenListIndex++;

    // ifLabelCounter = this->labelCounter;
    if (!this->compileStatements()) /*this->compileStatements();*/
      return false;

    // this->labelCounter = ifLabelCounter;

    if (!(this->tokenListKey() == "}"))
      return false;

    // this->labelCounter = ifLabelCounter;

    // this->writeToFile();
    this->tokenListIndex++;
  }
  // this->writeToFileFinishNonTerminal("</ifStatement>");
  /*Setting end label*/
  this->vmWritter.writeLabel(this->currentClass + "_" +
                             this->currentSubroutine + "_" + "end_if" + "_" +
                             std::to_string(ifLabelCounter - 1));
  // this->labelCounter = 0;
  return true;
}
bool CompilationEngine::compileWhile() {

  if (!(this->tokenListKey() == "while"))
    return false;

  this->vmWritter.writeLabel(this->currentClass + "_" +
                             this->currentSubroutine + "_" + "loop" + "_" +
                             std::to_string(this->labelCounter));

  // this->writeToFileFinishNonTerminal("<whileStatement>");
  // this->writeToFile();
  this->tokenListIndex++;

  /*Add label to return*/

  if (!(this->tokenListKey() == "("))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  int startExpressionIndex = this->tokenListIndex;

  //  this->flagIsDoStatement = false;
  if (!this->compileExpression()) /*this->compileExpression();*/
    return false;
  //  this->flagIsDoStatement = true;
  //
  /*Just to test something*/
  std::string expression = "";
  for (int i = startExpressionIndex; i < this->tokenListIndex; i++)
    expression.append(this->tokenList.at(i)->begin()->first);

  if (expression == "loop") {
    std::cout << "WHILE" << "\n";
    std::cout << expression << "\n";
  }
  /*When to put this is something I will figure it out after*/

  /*Handled by codeWrite*/
  // if (expression == "true")
  //   expression = "-1";
  // if (expression == "false")
  //   expression = "0";

  this->_codeWrite(expression);

  /*negating the condition*/
  this->vmWritter.writeArithmetic("~");
  /*Adding if goto label */
  this->vmWritter.writeIf(this->currentClass + "_" + this->currentSubroutine +
                          "_" + "Endloop" + "_" +
                          std::to_string(this->labelCounter));

  this->labelCounter++;

  // this->vmWritter.writeGoto();

  if (!(this->tokenListKey() == ")"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "{"))
    return false;
  // this->writeToFile();
  this->tokenListIndex++;

  /*For having memory of the loopcounter*/
  int loopLabelCounter = this->labelCounter;
  // this->flagIsDoStatement = false;
  if (!this->compileStatements()) /*this->compileStatements();*/
    return false;
  //  this->flagIsDoStatement = true;
  // this->labelCounter = loopLabelCounter;

  if (!(this->tokenListKey() == "}"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  this->vmWritter.writeGoto(this->currentClass + "_" + this->currentSubroutine +
                            "_" + "loop" + "_" +
                            std::to_string(loopLabelCounter - 1));
  this->vmWritter.writeLabel(this->currentClass + "_" +
                             this->currentSubroutine + "_" + "Endloop" + "_" +
                             std::to_string(loopLabelCounter - 1));

  // this->labelCounter = 0;
  // this->writeToFileFinishNonTerminal("</whileStatement>");
  return true;
}
bool CompilationEngine::compileDo() {

  if (!(this->tokenListKey() == "do"))
    return false;

  // this->writeToFileFinishNonTerminal("<doStatement>");
  // this->writeToFile();
  this->tokenListIndex++;

  int startExpressionIndex = this->tokenListIndex;

  this->flagIsDoStatement = true;
  if (!this->compileExpression())
    return false;
  this->flagIsDoStatement = false;

  /*Just to test something*/
  std::string expression = "";
  for (int i = startExpressionIndex; i < this->tokenListIndex; i++)
    expression.append(this->tokenList.at(i)->begin()->first);

  std::cout << expression << "\n";

  /*look ahead if has an string*/
  /*Needed for saving object */
  bool hasAString =
      (std::regex_search(expression, std::regex(R"(\".*\")"))) ? true : false;

  /*Saving state*/
  if (hasAString) {
    this->vmWritter.writePush("pointer", 0);
    this->vmWritter.writePop("temp", 2);
    // this->vmWritter.writePush("pointer", 1);
    // this->vmWritter.writePop("temp", 3);
  }

  this->_codeWrite(expression);

  if (!(this->tokenListKey() == ";"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  /*Adding the pop for the returned values that will be 0 in this case*/
  this->vmWritter.writePop("temp", 0);
  /*As a string creates another object then the object
   * pointed before needed */
  if (hasAString) {
    this->vmWritter.writePush("temp", 2);
    this->vmWritter.writePop("pointer", 0);
    // this->vmWritter.writePush("temp", 3);
    // this->vmWritter.writePop("pointer", 1);
  }

  // this->writeToFileFinishNonTerminal("</doStatement>");
  return true;
}
bool CompilationEngine::compileReturn() {

  if (!(this->tokenListKey() == "return"))
    return false;

  // this->writeToFileFinishNonTerminal("<returnStatement>");
  // this->writeToFile();
  this->tokenListIndex++;

  int startExpressionIndex = this->tokenListIndex;

  if (!this->compileExpression())
    return false;

  /*Just to test something*/
  std::string expression = "";
  for (int i = startExpressionIndex; i < this->tokenListIndex; i++)
    expression.append(this->tokenList.at(i)->begin()->first);

  std::cout << expression << "\n";
  this->_codeWrite(expression);

  if (!(this->tokenListKey() == ";"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  // this->writeToFileFinishNonTerminal("</returnStatement>");
  /**/
  // this->vmWritter.writePop("temp", 1);
  if (expression.empty())
    this->vmWritter.writePush("constant", 0);

  /*Pushing object reference if constructor*/
  if (expression == "this")
    this->vmWritter.writePush("pointer", 0);

  this->vmWritter.writeReturn();

  return true;
}

/*Needed in order to produce the correct narg number*/
void CompilationEngine::compileParameterList(int *nArgsCounter) {
  /* I think in here there is a mistake i had solved*/

  /*if is a method We will add this as argument*/
  if (this->currentSubroutineType == "method") {
    /*needs to be done if using a method and not a subroutine*/
    this->subroutineSymbolTable.setSymbol(
        this->subroutineSymbolTable.allocateSymbol());
    this->subroutineSymbolTable.getCurrentSymbol()->setKind("argument");
    this->subroutineSymbolTable.getCurrentSymbol()->setType(this->currentClass);
    this->subroutineSymbolTable.getCurrentSymbol()->setName("this");
    this->subroutineSymbolTable.addSymbol(
        this->subroutineSymbolTable.getCurrentSymbol());
    this->subroutineSymbolTable.setSymbol(nullptr);
  }

  /*Check there are no parameters*/
  if (this->tokenListKey() == ")") {

    // this->writeToFileStartNonTerminal("<parameterList>");
    // this->writeToFileFinishNonTerminal("</parameterList>");
    return;
  }

  /*Duplicated code needs to be fixed*/
  // this->subroutineSymbolTable.setSymbol(
  //     this->subroutineSymbolTable.allocateSymbol());
  // this->subroutineSymbolTable.getCurrentSymbol()->setKind("argument");
  // this->subroutineSymbolTable.getCurrentSymbol()->setType(this->currentClass);
  // this->subroutineSymbolTable.getCurrentSymbol()->setName("this");
  // this->subroutineSymbolTable.addSymbol(
  //     this->subroutineSymbolTable.getCurrentSymbol());
  // this->subroutineSymbolTable.setSymbol(nullptr);

  if (!(this->tokenListKey() == "int" || this->tokenListKey() == "char" ||
        this->tokenListKey() == "boolean" ||
        this->tokenListValue() == JackTypes::IDENTIFIER))
    return;

  this->subroutineSymbolTable.setSymbol(
      this->subroutineSymbolTable.allocateSymbol());
  /*Improve this*/
  this->subroutineSymbolTable.getCurrentSymbol()->setKind("argument");

  // this->writeToFileStartNonTerminal("<parameterList>");

  this->subroutineSymbolTable.getCurrentSymbol()->setType(this->tokenListKey());
  // this->writeToFile();
  this->tokenListIndex++;
  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return;

  this->subroutineSymbolTable.getCurrentSymbol()->setName(this->tokenListKey());
  this->subroutineSymbolTable.addSymbol(
      this->subroutineSymbolTable.getCurrentSymbol());
  this->subroutineSymbolTable.setSymbol(nullptr);
  // this->writeToFile();
  this->tokenListIndex++;

  while ((this->tokenListKey() == ",") &&
         (this->tokenListKey(1) == "int" || this->tokenListKey(1) == "char" ||
          this->tokenListKey(1) == "boolean" ||
          this->tokenListValue(1) == JackTypes::IDENTIFIER) &&
         /*offset */
         (this->tokenListValue(2) == JackTypes::IDENTIFIER)) {

    this->subroutineSymbolTable.setSymbol(
        this->subroutineSymbolTable.allocateSymbol());
    this->subroutineSymbolTable.getCurrentSymbol()->setKind("argument");
    this->subroutineSymbolTable.getCurrentSymbol()->setType(
        this->tokenListKey(1));
    this->subroutineSymbolTable.getCurrentSymbol()->setName(
        this->tokenListKey(2));
    this->subroutineSymbolTable.addSymbol(
        this->subroutineSymbolTable.getCurrentSymbol());
    this->subroutineSymbolTable.setSymbol(nullptr);

    // this->writeToFile();
    this->tokenListIndex++;
    // this->writeToFile();
    this->tokenListIndex++;
    // this->writeToFile();
    this->tokenListIndex++;
  }
  // this->writeToFileFinishNonTerminal("</parameterList>");

  return;
}
bool CompilationEngine::compileExpression() {
  /*if expression is empty*/
  if (this->tokenListKey() == ";")
    return true;

  // int startExpressionIndex = this->tokenListIndex;
  int iteration = 0;
  bool succesfull = true;

  // if (!this->flagIsDoStatement)
  // this->writeToFileStartNonTerminal("<expression>");

  /*for be working just now*/
  this->compileTerm(&iteration, &succesfull);
  if (!succesfull)
    return false;

  iteration = 0;
  succesfull = true;

  /*not like this because I need to update the index*/
  while (true) {
    if ((size_t)this->tokenListIndex > this->tokenList.size() - 1)
      break;

    if (!JackTypes::tokenIsOp(this->tokenListKey()))
      break;

    // this->writeToFile();
    this->tokenListIndex++;
    this->compileTerm(&iteration, &succesfull);
    if (!succesfull)
      return false;
  }
  if (!this->flagIsDoStatement) {
    // this->writeToFileFinishNonTerminal("</expression>");
    //  this->flagIsDoStatement = false; /*Hard to understand*/
  }

  // std::string expression = "";
  // for (int i = startExpressionIndex; i < this->tokenListIndex; i++)
  //   expression.append(this->tokenList.at(i)->begin()->first);
  //
  // std::cout << expression << "\n";
  // this->_codeWrite(expression);

  return true;
}
/*TEST with
 * x + g(2,y,-z)*5
 * a + b * c
 * x + y -2
 * foo(x,y+1,-7)
 * */

SymbolTable::Symbol *
CompilationEngine::_getSymbol(const std::string &symbolName) {
  SymbolTable::Symbol *symbol;
  symbol = this->subroutineSymbolTable.getSymbol(symbolName);
  if (symbol)
    return symbol;

  symbol = this->classSymbolTable.getSymbol(symbolName);
  if (symbol)
    return symbol;
  //
  return NULL;
}
std::string
CompilationEngine::_getSubroutineType(const std::string &subroutineName) {
  std::string functionType = "";
  try {
    functionType = this->subroutineTable.at(subroutineName);
  } catch (const std::out_of_range &oor) {
    functionType = "";
  }
  return functionType;
}
void CompilationEngine::_codeWrite(std::string &expression) {
  std::cout << expression << "\n";

  if (expression.empty())
    return;

  if (expression == "true") {
    expression = "-1";
    this->_codeWrite(expression);
    return;
  }

  if (expression == "false" || expression == "null") {
    expression = "0";
    this->_codeWrite(expression);
    return;
  }

  /*For handling strings*/
  /*Strings are always created through a kind of fucntion so*/
  if (JackTypes::tokenIsStringConstant(expression)) {
    /*Removing 2 for each \" */
    int stringSize = expression.size() - 2;
    this->vmWritter.writePush("constant", stringSize);
    this->vmWritter.writeCall("String.new", 1);
    this->vmWritter.writePop("pointer", 0);
    int charIntegerMapped;
    for (const auto character : expression) {
      if (character == '"')
        continue;

      std::cout << character << "\n";
      charIntegerMapped = (int)character;
      /*This argument passed*/
      this->vmWritter.writePush("pointer", 0);
      this->vmWritter.writePush("constant", charIntegerMapped);
      this->vmWritter.writeCall("String.appendChar", 2);
      this->vmWritter.writePop("pointer", 0);
    }
    this->vmWritter.writePush("pointer", 0);
    return;
  }

  if (JackTypes::tokenIsIntegerConstant(expression)) {
    this->vmWritter.writePush("constant", std::stoi(expression));
    return;
  }
  /*Not correct is considering functions*/
  /*to remove \( \)*/
  /*identifier regex*/
  // std::string identifierRegex = R"([a-zA-Z])";

  /*to improve*/
  std::regex operators = std::regex(R"(~|\+|\-|\*|\/|&|\||<|>|=)");
  std::regex arrayDelimeters = std::regex(R"(\[|\])");

  if (!std::regex_match(expression, std::regex(R"(^[0-9].*)")) &&
      !std::regex_match(expression, std::regex(R"(.*\(.*\).*)")) &&
      !std::regex_search(expression, operators) &&
      !std::regex_search(expression, arrayDelimeters)) {
    SymbolTable::Symbol *symbol = this->_getSymbol(expression);

    if (symbol)
      this->vmWritter.writePush(symbol->kind, symbol->posInSegment);

    return;
  }

  /* so is
   * a+b(...)
   * a(...)+b
   * aaa(...)+b(....)
   * f(......)
   *
   * */

  // * + a -> [x]
  if (std::regex_match(expression.substr(0, 1), std::regex(R"([~|-])"))) {

    std::string _op;
    std::string right;
    _op = expression.substr(0, 1);
    right = expression.substr(1);
    this->_codeWrite(right);
    /* - can be used as binary operator or unary operator*/
    (_op == "-") ? this->vmWritter.writeArithmetic(_op + "" + _op)
                 : this->vmWritter.writeArithmetic(_op);
    return;
  }

  // * x + y -> first [x]
  /*Error because not considering ~ operator*/
  const std::regex _operatorsPatternRegex(R"([\+|\~|\-|\*|\/|&|\||<|>|=])");
  if ((expression.find_first_of('(') == std::string::npos &&
       std::regex_search(expression, _operatorsPatternRegex))) {

    std::string _op;
    std::string right;
    std::stringstream left;
    std::string lefts;
    size_t i = 0;
    while (i < expression.size() &&
           !std::regex_match(expression.substr(i, 1), _operatorsPatternRegex)) {
      left << expression.substr(i, 1);
      i++;
    }
    lefts = left.str();
    _op = expression.substr(lefts.size(), 1);
    right = expression.substr(lefts.size() + 1);
    this->_codeWrite(lefts);
    this->_codeWrite(right);
    this->vmWritter.writeArithmetic(_op);
    return;
  }

  // this code will break eventually

  /*For handling arrays*/
  // std::regex arrayDelimeters = std::regex(R"(\[|\])");

  // if (std::regex_search(expression, arrayDelimeters) &&
  //       !std::regex_search(expression.substr(expression.find_last_of("]")),
  //                          _operatorsPatternRegex) &&
  //       !std::regex_search(expression.substr(0,
  //       expression.find_first_of("[")),
  //                          _operatorsPatternRegex)) {
  //     /*Debug*/
  //     std::string lef = expression.substr(expression.find_last_of("]"));
  //     std::string rig = expression.substr(0, expression.find_first_of("["));
  //
  //     /*Easy case*/
  //     std::string lefts = expression.substr(0,
  //     expression.find_first_of("[")); std::string right = expression.substr(
  //         expression.find_first_of("[") + 1,
  //         expression.find_last_of("]") - expression.find_first_of("[") - 1);
  //
  //     this->_codeWrite(lefts);
  //     this->_codeWrite(right);
  //     this->vmWritter.writeArithmetic("add");
  //     this->vmWritter.writePop("pointer", 1);
  //     this->vmWritter.writePush("that", 0);
  //     return;
  //   }

  if (expression.find("[") != std::string::npos && expression.find("]") &&
      std::string::npos &&
      expression.find_first_of("[") < expression.find_first_of("(")) {
    std::string resultingExpression =
        expression.substr(expression.find_first_of('['),
                          expression.size() - expression.find_first_of('['));
    std::string beforeOpenPar =
        expression.substr(0, expression.find_first_of('['));
    // * a+b(...)
    if (std::regex_search(beforeOpenPar, _operatorsPatternRegex)) {
      int i = 0;
      for (; !std::regex_match(expression.substr(i, 1), _operatorsPatternRegex);
           i++)
        ;
      std::cout << expression.substr(0, i) << "\n";
      std::string lefts = expression.substr(0, i);
      std::string _op = expression.substr(i, 1);
      std::string right = expression.substr(i + 1);
      this->_codeWrite(lefts);
      this->_codeWrite(right);
      this->vmWritter.writeArithmetic(_op);
      return;
    }

    // * a(...)+b
    // * aaa(...)+b(....)
    // * f(......)
    std::stack<char> parenthesisStack{};
    std::stringstream str;
    size_t i = 0;
    str << resultingExpression.at(i);
    parenthesisStack.push(resultingExpression.at(i++));
    while (!parenthesisStack.empty() && i <= resultingExpression.size() - 1) {
      if (resultingExpression.at(i) == ']') {
        parenthesisStack.pop();
      }
      if (resultingExpression.at(i) == '[') {
        parenthesisStack.push(i);
      }
      str << resultingExpression.at(i);
      i++;
    }
    i--;
    // * a(...)+b
    // * aaa(...)+b(....)
    if (expression.size() - 1 > i + expression.find_first_of('[')) {
      std::string lefts =
          expression.substr(0, i + expression.find_first_of('[') + 1);
      std::cout << lefts << "\n";
      std::string _op =
          expression.substr(i + expression.find_first_of('[') + 1, 1);
      std::cout << _op << "\n";
      std::string right =
          expression.substr(i + expression.find_first_of('[') + 2);
      std::cout << right << "\n";
      this->_codeWrite(lefts);
      this->_codeWrite(right);
      this->vmWritter.writeArithmetic(_op);
      return;
    }
    /*a[.........]*/
    if (expression.size() - 1 == i + expression.find_first_of('[')) {

      /*Easy case*/
      std::string lefts = expression.substr(0, expression.find_first_of("["));
      std::string right = expression.substr(
          expression.find_first_of("[") + 1,
          expression.find_last_of("]") - expression.find_first_of("[") - 1);

      this->_codeWrite(lefts);
      this->_codeWrite(right);
      this->vmWritter.writeArithmetic("add");
      this->vmWritter.writePop("pointer", 1);
      this->vmWritter.writePush("that", 0);
      return;
    }
    return;
  }

  // * a+b(...)
  if (expression.find("(") != std::string::npos && expression.find(")") &&
      std::string::npos &&
      expression.find_first_of("(") < expression.find_first_of("[")) {
    std::string resultingExpression =
        expression.substr(expression.find_first_of('('),
                          expression.size() - expression.find_first_of('('));
    std::string beforeOpenPar =
        expression.substr(0, expression.find_first_of('('));
    // * a+b(...)
    if (std::regex_search(beforeOpenPar, _operatorsPatternRegex)) {
      int i = 0;
      for (; !std::regex_match(expression.substr(i, 1), _operatorsPatternRegex);
           i++)
        ;
      std::cout << expression.substr(0, i) << "\n";
      std::string lefts = expression.substr(0, i);
      std::string _op = expression.substr(i, 1);
      std::string right = expression.substr(i + 1);
      this->_codeWrite(lefts);
      this->_codeWrite(right);
      this->vmWritter.writeArithmetic(_op);
      return;
    }

    // * a(...)+b
    // * aaa(...)+b(....)
    // * f(......)
    std::stack<char> parenthesisStack{};
    std::stringstream str;
    size_t i = 0;
    str << resultingExpression.at(i);
    parenthesisStack.push(resultingExpression.at(i++));
    while (!parenthesisStack.empty() && i <= resultingExpression.size() - 1) {
      if (resultingExpression.at(i) == ')') {
        parenthesisStack.pop();
      }
      if (resultingExpression.at(i) == '(') {
        parenthesisStack.push(i);
      }
      str << resultingExpression.at(i);
      i++;
    }
    i--;
    // * a(...)+b
    // * aaa(...)+b(....)
    if (expression.size() - 1 > i + expression.find_first_of('(')) {
      std::string lefts =
          expression.substr(0, i + expression.find_first_of('(') + 1);
      std::cout << lefts << "\n";
      std::string _op =
          expression.substr(i + expression.find_first_of('(') + 1, 1);
      std::cout << _op << "\n";
      std::string right =
          expression.substr(i + expression.find_first_of('(') + 2);
      std::cout << right << "\n";
      this->_codeWrite(lefts);
      this->_codeWrite(right);
      this->vmWritter.writeArithmetic(_op);
      return;
    }

    /*(........)&(.......)*/
    if ((expression.substr(0, 1) == "(" &&
         expression.substr(expression.size() - 1, 1) == ")")) {
      expression = expression.substr(1, expression.size() - 2);
      return this->_codeWrite(expression);
    }

    // * f(......)
    if (expression.substr(i + expression.find_first_of('('), 1) == ")") {
      std::cout << expression.substr(expression.find_first_of('(') + 1, i - 1)
                << "\n";
      std::stringstream streamExpression = std::stringstream(
          expression.substr(expression.find_first_of('(') + 1, i - 1));

      /*This was moved because it was neede above all determine
       * if it was a method, because in that case this parameter needs to
       * be pushed first*/
      std::string functionName =
          expression.substr(0, expression.find_first_of("("));

      int nArgs = 0;
      if (streamExpression.str().empty())
        nArgs = 0;

      else if (streamExpression.str().find(',') == std::string::npos)
        nArgs = 1;
      else {
        std::string tmpStr(streamExpression.str());
        for (size_t i = 0; i < tmpStr.size(); i++) {
          if (tmpStr.at(i) == ',')
            nArgs += 1;
        }
        nArgs++;
      }
      /*For calling passing this as extra argument*/

      /*If function is called without the className is a method*/ /*This was the
      mistake*/
      /*if function is called through an object is also a method*/

      /*I need to check what is the type of the function*/ /*I could createa a
      table with the functions signature but man*/
      if (functionName.find_first_of(".") == std::string::npos) {
        /*This needed to be fixed*/
        /*Check function to be called type*/
        // std::string functionType = this->subroutineTable.at(functionName);
        std::string functionType = this->_getSubroutineType(functionName);
        if (functionType == "method") {
          this->vmWritter.writePush("pointer", 0);
          nArgs++;
        }
        /*If is a method and and is in the same class the call the function
         * ClassName.functionName*/
        functionName = this->currentClass + "." + functionName;
      } else if (this->_getSymbol(
                     functionName.substr(0, functionName.find_first_of(".")))) {
        SymbolTable::Symbol *s = this->_getSymbol(
            functionName.substr(0, functionName.find_first_of(".")));
        this->vmWritter.writePush(s->kind, s->posInSegment);
        nArgs++;
        /*When the method is called through the object we need to identify the
         * class of the object to call the correct method */
        functionName = s->type + "." +
                       functionName.substr(functionName.find_first_of(".") + 1);
      }
      /**/
      /*It will later organize*/
      std::string element = "";
      while (std::getline(streamExpression, element, ',')) {
        /*Save object pointer in case is an string*/
        this->_codeWrite(element);
      }
      this->vmWritter.writeCall(functionName, nArgs);

      return;
    }
    return;
  }
}

void CompilationEngine::compileTerm(int *iteration, bool *succesfull) {

  /*this will be the same */
  /*never theless the tokenListIndex will be incremented because is global*/

  // int localIteration = *iteration;

  if ((size_t)this->tokenListIndex > this->tokenList.size() - 1) {
    return;
  }

  /*First check that term is correct*/
  if (JackTypes::INT_CONST == this->tokenListValue() ||
      JackTypes::STRING_CONST == this->tokenListValue() ||
      JackTypes::KEYWORD == this->tokenListValue()) {
    // if (!this->flagIsDoStatement)
    // this->writeToFileStartNonTerminal("<term>");
    // this->writeToFile();
    *iteration += 1;
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    //    if (!this->flagIsDoStatement)
    // this->writeToFileFinishNonTerminal("</term>");
    return;
  }

  if (this->tokenListValue() == JackTypes::IDENTIFIER &&
      this->tokenListKey(1) == "[") {
    // if (!this->flagIsDoStatement)
    // this->writeToFileStartNonTerminal("<term>");
    // this->writeToFile();
    this->tokenListIndex++;
    if (this->tokenListKey() == "[") {
      // this->writeToFile();
      this->tokenListIndex++;
      if (!this->compileExpression()) {
        *succesfull = false;
        return;
      }
      if (!(this->tokenListKey() == "]")) {
        *succesfull = false;
        return;
      }
      *iteration += 1;
      // this->writeToFile();
      this->tokenListIndex++;
      this->compileTerm(iteration, succesfull);
      //    if (!this->flagIsDoStatement)
      // this->writeToFileFinishNonTerminal("</term>");
      return;
    }
  }
  if ((this->tokenListValue() == JackTypes::IDENTIFIER &&
       this->tokenListKey(1) == "(")) {
    // if (!this->flagIsDoStatement)
    // this->writeToFileStartNonTerminal("<term>");
    if (!this->_compileSubroutineCall()) {
      *succesfull = false;
      return;
    }
    *iteration += 1;
    this->compileTerm(iteration, succesfull);
    //    if (!this->flagIsDoStatement)
    // this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  if ((this->tokenListValue() == JackTypes::IDENTIFIER &&
       this->tokenListKey(1) == ".")) {
    // if (!this->flagIsDoStatement)
    // this->writeToFileStartNonTerminal("<term>");
    // this->writeToFile();
    this->tokenListIndex++;
    // this->writeToFile();
    this->tokenListIndex++;
    if (!this->_compileSubroutineCall()) {
      *succesfull = false;
      return;
    }
    *iteration += 1;
    this->compileTerm(iteration, succesfull);
    //    if (!this->flagIsDoStatement)
    // this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  if (this->tokenListValue() == JackTypes::IDENTIFIER) {
    // if (!this->flagIsDoStatement)
    // this->writeToFileStartNonTerminal("<term>");
    // this->writeToFile();
    *iteration += 1;
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    //    if (!this->flagIsDoStatement)
    // this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  if (this->tokenListKey() == "(") {
    // if (!this->flagIsDoStatement)
    // this->writeToFileStartNonTerminal("<term>");
    // this->writeToFile();
    this->tokenListIndex++;
    if (!this->compileExpression()) {
      *succesfull = false;
      return;
    }
    if (!(this->tokenListKey() == ")")) {
      *succesfull = false;
      return;
    }
    *iteration += 1;
    // this->writeToFile();
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    //    if (!this->flagIsDoStatement)
    // this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  if (JackTypes::tokenIsUnaryOp(this->tokenListKey()) && *iteration == 0) {
    // if (!this->flagIsDoStatement)
    // this->writeToFileStartNonTerminal("<term>");
    // this->writeToFile();
    *iteration += 1;
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    //    if (!this->flagIsDoStatement)
    // this->writeToFileFinishNonTerminal("</term>");
    return;
  }

  if (JackTypes::tokenIsKeywordConstant(this->tokenListKey())) {
    // if (!this->flagIsDoStatement)
    // this->writeToFileStartNonTerminal("<term>");
    // this->writeToFile();
    *iteration += 1;
    this->tokenListIndex++;
    this->compileTerm(iteration, succesfull);
    //    if (!this->flagIsDoStatement)
    // this->writeToFileFinishNonTerminal("</term>");
    return;
  }
  return;
}

/*Personal idea*/
bool CompilationEngine::_compileSubroutineCall() {

  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "("))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  bool old_state_flag = this->flagIsDoStatement;

  this->flagIsDoStatement = false;
  this->compileExpressionList();
  this->flagIsDoStatement = old_state_flag;

  if (!(this->tokenListKey() == ")"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;
  return true;
}

bool CompilationEngine::compileVarDec() {

  /*Kind is always var?*/
  if (!(this->tokenListKey() == "var"))
    return false;

  this->subroutineSymbolTable.setSymbol(
      this->subroutineSymbolTable.allocateSymbol());

  // this->writeToFileFinishNonTerminal("<varDec>");

  std::string kind = this->tokenListKey();
  this->subroutineSymbolTable.getCurrentSymbol()->setKind(this->tokenListKey());
  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListKey() == "int" || this->tokenListKey() == "char" ||
        this->tokenListKey() == "boolean" ||
        this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  std::string type = this->tokenListKey();

  /*Adding this in method (arg0)*/

  this->subroutineSymbolTable.getCurrentSymbol()->setType(this->tokenListKey());
  // this->writeToFile();
  this->tokenListIndex++;

  if (!(this->tokenListValue() == JackTypes::IDENTIFIER))
    return false;

  this->subroutineSymbolTable.getCurrentSymbol()->setName(this->tokenListKey());
  this->subroutineSymbolTable.addSymbol(
      this->subroutineSymbolTable.getCurrentSymbol());
  this->subroutineSymbolTable.setSymbol(nullptr);

  // this->writeToFile();
  this->tokenListIndex++;

  while ((this->tokenListKey() == ",") &&
         /*offset */
         (this->tokenListValue(1) == JackTypes::IDENTIFIER)) {

    this->subroutineSymbolTable.setSymbol(
        this->subroutineSymbolTable.allocateSymbol());
    this->subroutineSymbolTable.getCurrentSymbol()->setKind(kind);
    this->subroutineSymbolTable.getCurrentSymbol()->setType(type);
    this->subroutineSymbolTable.getCurrentSymbol()->setName(
        this->tokenListKey(1));
    this->subroutineSymbolTable.addSymbol(
        this->subroutineSymbolTable.getCurrentSymbol());
    this->subroutineSymbolTable.setSymbol(nullptr);

    // this->writeToFile();
    this->tokenListIndex++;
    // this->writeToFile();
    this->tokenListIndex++;
  }

  if (!(this->tokenListKey() == ";"))
    return false;

  // this->writeToFile();
  this->tokenListIndex++;

  // this->subroutineSymbolTable.resetSymbolTable();

  // this->writeToFileFinishNonTerminal("</varDec>");

  return true;
}
void CompilationEngine::compileExpressionList() {
  // this->writeToFileStartNonTerminal("<expressionList>");
  if (this->tokenListKey() == ")") {
    // this->writeToFileFinishNonTerminal("</expressionList>");
    return;
  }

  /*code*/
  if (!this->compileExpression())
    return;

  while (true) {
    if (!(this->tokenListKey() == ","))
      break;
    // this->writeToFile();
    this->tokenListIndex++;
    // this->flagIsDoStatement = false;
    if (!this->compileExpression())
      break;
  }

  // this->writeToFileFinishNonTerminal("</expressionList>");

  return;
}

const std::vector<std::map<std::string, JackTypes::TokenType> *> &
CompilationEngine::getTokenList() {
  return this->tokenList;
}
CompilationEngine::~CompilationEngine() {
  std::cout << "Calling compilation engine destructor" << "\n";
}
void CompilationEngine::populateSubroutineTable() {
#define KEY_VALUE(index) (this->tokenList.at(index)->begin()->first)
  for (size_t i = 0; i < this->tokenList.size(); i++) {
    if (KEY_VALUE(i) == "method" || KEY_VALUE(i) == "function") {
      this->subroutineTable.insert({KEY_VALUE(i + 2), KEY_VALUE(i)});
    }
  }
#undef KEY_VALUE
}
